// Writes docs/INTERNAL_LINKING_MAP.md from the location records.
// Run: npm run docs:links   (after adding or changing a location)
import { writeFileSync } from "node:fs";
import { getCaseStudy } from "../data/case-studies.ts";
import { getIndustry } from "../data/industries/index.ts";
import { citiesOf, getLocation, locationPath, locations, markets } from "../data/locations/index.ts";
import { localServicePath, localServicesIn } from "../data/locations/services/index.ts";
import { getArticle } from "../data/resources/index.ts";
import { getService } from "../data/services/index.ts";
import type { LocationRecord } from "../types/index.ts";

const inline = (l: LocationRecord) => [...new Set([...JSON.stringify(l).matchAll(/\]\((\/[^)\s]*)\)/g)].map((m) => m[1]))].sort();
const list = (items: string[]) => (items.length ? items.map((i) => `- ${i}`).join("\n") : "- none");
const inbound = new Map<string, Set<string>>();
const note = (to: string, from: string) => inbound.set(to, (inbound.get(to) ?? new Set()).add(from));

for (const l of locations) {
  const from = locationPath(l);
  for (const r of l.related) note(r, from);
  for (const p of inline(l).filter((p) => p.startsWith("/digital-marketing-agency-"))) note(p, from);
  if (l.kind === "city") {
    note(locationPath(getLocation(l.parent!)!), from);
    for (const n of l.nearby ?? []) note(`/digital-marketing-agency-${n}/`, from);
  } else for (const c of citiesOf(l.slug)) note(locationPath(c), from);
}

function section(l: LocationRecord) {
  const path = locationPath(l);
  const cities = l.kind === "city" ? [] : citiesOf(l.slug);
  const local = localServicesIn(l.slug);
  return `### ${l.name} \`${path}\`

Primary keyword: ${l.seo.primaryKeyword}

**Services** (service rows, each with a reason specific to this place)
${list(l.services.map((s) => `[${getService(s.slug)!.name}](/${s.slug}/) as "${s.title}"`))}

**Industries**
${list(l.industries.map((i) => `[${getIndustry(i.slug)!.name}](/industries/${i.slug}/)`))}

**Locations linked from this page**
${list([
  ...(l.kind === "city" ? [`Parent: /digital-marketing-agency-${l.parent}/`] : []),
  ...cities.map((c) => `City: ${locationPath(c)}`),
  ...(l.nearby ?? []).map((n) => `Nearby: /digital-marketing-agency-${n}/`),
  ...l.related.map((r) => `Related: ${r}`),
  ...local.map((p) => `Service here: ${localServicePath(p)}`),
])}

**Links inside the copy**
${list(inline(l))}

**Case studies and scenarios**
${list(l.caseStudies.map((c) => `/case-studies/${c}/ (${getCaseStudy(c)!.illustrative ? "illustrative scenario, noindex" : "published"})`))}

**Resources**
${list(l.resources.map((r) => `[${getArticle(r)!.title}](/resources/${r}/)`))}

**Linked from** ${[...(inbound.get(path) ?? [])].sort().join(", ") || "the locations index only"}
`;
}

const body = `# Internal linking map: locations

GENERATED by \`scripts/build-linking-map.ts\` from \`data/locations\`. Do not edit by hand; run \`npm run docs:links\`.

Every location page also links to the locations index (breadcrumb), the growth audit (hero, closing band and sticky bar), the services index and the methodology page. Those are the same on every page and are not repeated below.

${locations.length} location pages: ${markets.length} markets and ${locations.length - markets.length} cities.

${markets.map((m) => `## ${m.name}\n\n${[m, ...citiesOf(m.slug)].map(section).join("\n")}`).join("\n")}`;

writeFileSync(new URL("../docs/INTERNAL_LINKING_MAP.md", import.meta.url), body);
console.log(`docs/INTERNAL_LINKING_MAP.md written for ${locations.length} locations`);
